### PR TITLE
feat: get parties in discovery inbound and outbound requests

### PR DESCRIPTION
**Pull request by elijah0kello**
- This PR implements the inbound and outbound requests for the token adapter get parties function in discovery

### CODE REVIEW

**Comment by elijah0kello** [comment]
@vijayg10 kindly review the PR. The pipeline is taking quite long to execute. I have noticed. Don't know why.

**Comment by elijah0kello** [comment]
Pipeline is failing with this error

Screenshot 2024-02-14 at 16 19 24

**Comment by elijah0kello** [comment]
@vijayg10 ci is now passing

**Review by vijayg10 — APPROVED** [review]

**Comment by elijah0kello** [comment]
Thanks @vijayg10

**Pull request merged**
